import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import SearchIcon from '@mui/icons-material/Search';
import { faSearch, faPhone, faUser, faExternalLink, faInr } from "@fortawesome/free-solid-svg-icons"; // Import the FontAwesomeIcon component
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome"; // import the icons you need

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>leverage Edu</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>

       <div className={styles.ad}>
        <p className={styles.adTitle}>Leverage Edu Scholarship Worth <span className={styles.rupeeIcon}><FontAwesomeIcon icon={faInr}></FontAwesomeIcon></span> 7,00,00,000 </p>
        <button className={styles.adButton}>Apply now</button>
       </div>

       <div className={styles.header}>
        <div className={styles.headerLogo}><img src='https://tse1.mm.bing.net/th?id=OIP.BBY7G4-kDMabODYCx214GAHaDt&pid=Api&P=0&h=180' width={80}  alt='icon'></img></div>
        <div className={styles.headerTab}>study Abroad</div>
        <div className={styles.headerTab}>Accommodation</div>
        <div className={styles.headerTab}>Test Prep</div>
        <div className={styles.headerTab}>Finanace</div>
        <div className={styles.headerTab}>Community</div>
        <div className={styles.headerTab}>Products</div>
        <div className={styles.headerTab}>More</div>
        <div className={styles.headerIcon}>
          <FontAwesomeIcon icon={faSearch}></FontAwesomeIcon>
        </div>
        <div className={styles.headerIcon}>
        <FontAwesomeIcon icon={faPhone}></FontAwesomeIcon>
        </div>
        <div className={styles.headerIcon}>
        <FontAwesomeIcon icon={faUser}></FontAwesomeIcon>
        </div>
       </div>
       <div className={styles.halfLine}></div>

      <div className={styles.mainContainer}>

       <div className={styles.mainLeft}>
        <div className={styles.mainLHeading}>
          <h1>FIRST IN THE <br/> FAMILY</h1>
        </div>
        <div className={styles.mainLDis}>
          <p>They are the global citizens of <br/> tomorrow. Start your study <br/> abroad journey today.</p>
        </div>
        <div className={styles.mainLIcon}>
          <div className={styles.linkIcon}><FontAwesomeIcon icon={faExternalLink}></FontAwesomeIcon></div>
          <p className={styles.mainLIconLive}>Live on</p>
          <Image src='/dds.png' width={50} height={50} alt='disney'></Image>
        </div>
        <div className={styles.mainLButton}>
          <button className={styles.mainLButtonFree}> Get Your Shortlist for FREE</button>
        </div>
        <div className={styles.mainLButton}>
          <button className={styles.mainLButtonExpert}> Talk to an Expert </button>
        </div>
        <div className={styles.mainLBottomDis}>
          <p> 95% of our students get an admit in less than 4 vweeks</p>
        </div>
        <div className={styles.mainLBottomGlobal}>
          <p> Our students finished university to work at global office of:</p>
        </div>
        <div className={styles.mainLBottomOffice}>
         
        </div>

       </div>

       <div className={styles.mainRight}>
        <div className={styles.mainRImgContainer1}></div>
        <div className={styles.mainRImgContainer2}></div>
        <div className={styles.mainRImgContainer3}></div>
        <div className={styles.mainRImgContainer4}></div>
        <div className={styles.mainRImgContainer5}></div>
        <div className={styles.mainRImgContainer6}></div>
       </div>
      </div>
      </main>
    </>
  )
}

/*
 <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>src/pages/index.js</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Docs <span>-&gt;</span>
            </h2>
            <p>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Learn <span>-&gt;</span>
            </h2>
            <p>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Templates <span>-&gt;</span>
            </h2>
            <p>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Deploy <span>-&gt;</span>
            </h2>
            <p>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
*/
